export const articles = [
  {
    slug: "5-alasan-umkm-butuh-website-2026",
    title: "5 Alasan UMKM Wajib Punya Website di 2026",
    category: "Bisnis Digital",
    catColor: "#0d9488",
    date: "5 Jun 2026",
    readTime: "5 menit",
    excerpt: "Di era digital ini, bisnis tanpa website seperti toko tanpa papan nama. Pelajari mengapa website bukan lagi kemewahan, tapi kebutuhan utama UMKM.",
    cover: "from-teal-500 to-emerald-600",
    emoji: "🚀",
    content: [
      { type:"p", text:"Pernah mencari restoran, bengkel, atau salon di Google sebelum pergi ke sana? Hampir semua orang melakukannya. Survei Google Indonesia 2025 menunjukkan bahwa 78% konsumen Indonesia mencari informasi produk dan jasa secara online sebelum membuat keputusan pembelian — baik online maupun offline." },
      { type:"p", text:"Artinya, bisnis Anda dinilai bahkan sebelum calon pelanggan bertemu Anda. Dan jika bisnis Anda tidak hadir di internet dengan cara yang profesional, calon pelanggan itu akan beralih ke kompetitor yang lebih mudah ditemukan." },
      { type:"h2", text:"1. Kredibilitas Instan yang Tidak Bisa Dibohongi" },
      { type:"p", text:"Coba bayangkan dua situasi: Anda mencari jasa katering untuk acara pernikahan. Opsi pertama hanya punya nomor WhatsApp dan foto produk di Instagram. Opsi kedua punya website profesional dengan portofolio lengkap, testimoni klien, paket harga yang jelas, dan nomor telepon yang terverifikasi. Mana yang lebih Anda percaya untuk acara sebesar pernikahan?" },
      { type:"p", text:"Riset Stanford University membuktikan: 75% orang menilai kredibilitas sebuah bisnis hanya dari tampilan website-nya. Bukan dari kualitas produk, bukan dari harga, tapi dari website. Ini berarti bisnis tanpa website — atau dengan website yang buruk — sudah kalah sebelum bertanding." },
      { type:"h2", text:"2. Karyawan Terbaik yang Bekerja 24 Jam Gratis" },
      { type:"p", text:"Karyawan Anda pulang pukul 17.00. Toko Anda tutup tengah malam. Tapi website Anda? Tidak pernah istirahat. Calon pelanggan dari Surabaya bisa melihat katalog produk Anda pukul 2 pagi, membaca testimoni, membandingkan harga, dan memutuskan untuk menghubungi Anda besok pagi." },
      { type:"p", text:"Setiap malam saat Anda tidur, website Anda menjawab pertanyaan 'berapa harganya?', menampilkan portofolio terbaik Anda, dan meyakinkan calon pelanggan bahwa bisnis Anda adalah pilihan yang tepat. Tidak ada gaji, tidak ada cuti, tidak ada lembur." },
      { type:"h2", text:"3. Pasar yang Tidak Terbatas Geografis" },
      { type:"p", text:"Warung soto Anda di Jogja hanya bisa melayani orang yang lewat di jalan itu. Tapi kalau Anda punya website dengan foto makanan yang menggugah selera dan cerita di balik resep warisan keluarga, traveler dari Jakarta yang akan berkunjung ke Jogja minggu depan bisa menemukan warung Anda lewat Google dan langsung menjadikannya destinasi wajib." },
      { type:"p", text:"Lebih jauh lagi: bisnis produk seperti kerajinan tangan, fashion, atau makanan oleh-oleh bisa menjual ke seluruh Indonesia bahkan ke luar negeri — hanya dengan website yang dioptimalkan dengan benar." },
      { type:"h2", text:"4. Investasi Pemasaran Paling Efisien" },
      { type:"p", text:"Iklan koran: habis dibaca, dibuang. Brosur: sering langsung masuk tempat sampah. Spanduk: hilang dari ingatan dalam hitungan detik. Tapi artikel blog yang Anda tulis hari ini tentang 'tips memilih katering pernikahan' bisa mendatangkan calon pelanggan organik selama 5 tahun ke depan — tanpa biaya iklan tambahan." },
      { type:"p", text:"ROI (Return on Investment) website jauh melampaui media iklan konvensional. Biaya pembuatan website satu kali bisa menghasilkan ribuan leads selama bertahun-tahun. Tidak ada media pemasaran lain yang bisa menandingi efisiensi ini." },
      { type:"h2", text:"5. Data Nyata untuk Keputusan Bisnis yang Lebih Cerdas" },
      { type:"p", text:"Dengan Google Analytics di website Anda, Anda bisa mengetahui: 300 orang mengunjungi halaman produk A hari ini tapi hanya 3 yang menghubungi — berarti ada masalah di halaman itu. Atau: 80% pengunjung datang dari pencarian 'katering murah Jakarta' — berarti Anda harus fokus mengoptimalkan kata kunci itu." },
      { type:"p", text:"Data ini tidak bisa Anda dapatkan dari jualan lewat WhatsApp atau Instagram saja. Website memberi Anda 'mata' untuk melihat perilaku calon pelanggan dan membuat keputusan bisnis berdasarkan fakta, bukan perasaan." },
      { type:"cta", text:"Sudah yakin bisnis Anda butuh website? Cek estimasi biayanya sekarang — transparan dan tanpa biaya tersembunyi." },
    ],
  },
  {
    slug: "berapa-biaya-buat-website-panduan-harga",
    title: "Berapa Biaya Buat Website? Panduan Harga Jujur untuk UMKM",
    category: "Tips & Panduan",
    catColor: "#f97316",
    date: "3 Jun 2026",
    readTime: "6 menit",
    excerpt: "Bingung dengan harga jasa web yang beragam? Dari ratusan ribu sampai puluhan juta? Panduan ini menjelaskan apa saja yang mempengaruhi biaya website secara jujur.",
    cover: "from-orange-500 to-amber-500",
    emoji: "💰",
    content: [
      { type:"p", text:"'Mas, bikin website berapa?' Pertanyaan simpel yang jawabannya bikin pusing. Ada yang bilang Rp 300.000, ada yang Rp 3.000.000, ada yang Rp 30.000.000. Semuanya bilang bisa bikin website profesional. Apa yang membedakan mereka?" },
      { type:"p", text:"Artikel ini tidak akan memberikan jawaban 'tergantung'. Kami akan breakdown secara jujur apa yang Anda dapat di setiap kisaran harga, dan bagaimana memilih yang tepat untuk bisnis Anda." },
      { type:"h2", text:"Mengapa Harga Website Sangat Bervariasi?" },
      { type:"p", text:"Website adalah produk custom — seperti membangun rumah. Rumah tipe 36 sangat berbeda dengan rumah mewah 500m², meski keduanya sama-sama disebut 'rumah'. Faktor yang menentukan harga: kompleksitas desain, jumlah halaman, fitur yang dibutuhkan, teknologi yang digunakan, pengalaman developer, dan layanan purna jual." },
      { type:"h2", text:"Kisaran Harga dan Apa yang Anda Dapat" },
      { type:"p", text:"Rp 300.000 – Rp 800.000: Biasanya menggunakan template WordPress gratis dengan kustomisasi minimal. Cocok untuk 'sekadar ada di internet' tapi tidak untuk bisnis serius. Risiko: desain generik, loading lambat, tidak SEO-friendly, sulit dikustomisasi." },
      { type:"p", text:"Rp 800.000 – Rp 2.500.000: Landing page atau company profile sederhana dengan desain yang lebih dipersonalisasi. Sudah cukup untuk UMKM yang baru mulai go digital. Anda mendapat website yang berfungsi, mobile-friendly, dan bisa menghasilkan leads." },
      { type:"p", text:"Rp 2.500.000 – Rp 8.000.000: Website multi-halaman dengan fitur lengkap: blog, form kontak, galeri, integrasi WhatsApp, optimasi SEO dasar. Cocok untuk bisnis yang ingin tampil profesional dan mulai bersaing di pencarian Google." },
      { type:"p", text:"Rp 8.000.000 – Rp 25.000.000: Toko online custom, web app dengan fitur khusus, atau website dengan sistem admin. Untuk bisnis yang butuh fungsionalitas spesifik dan skalabilitas jangka panjang." },
      { type:"p", text:"Di atas Rp 25.000.000: Enterprise-level, platform e-commerce besar, atau aplikasi web kompleks dengan integrasi sistem. Biasanya untuk perusahaan menengah ke atas." },
      { type:"h2", text:"Yang Sering Tidak Masuk di Harga Awal" },
      { type:"p", text:"Ini yang sering bikin kaget: domain (.com Rp 150.000–200.000/tahun, .id Rp 200.000–400.000/tahun), hosting (Rp 200.000–1.000.000/tahun), SSL certificate (beberapa sudah gratis, beberapa berbayar), dan maintenance rutin. Pastikan Anda tanyakan semua komponen ini sebelum deal." },
      { type:"h2", text:"Tanda Developer yang Harus Anda Hindari" },
      { type:"p", text:"Waspada jika: harga sangat murah tanpa penjelasan mengapa, tidak ada portofolio yang bisa dikunjungi, tidak ada kejelasan soal kepemilikan file dan domain setelah selesai, tidak ada kontrak tertulis, atau meminta full payment di awal sebelum pekerjaan dimulai." },
      { type:"h2", text:"Cara Mendapat Nilai Terbaik" },
      { type:"p", text:"Bukan berarti cari yang termurah. Cari yang paling sesuai kebutuhan dengan harga yang masuk akal. Tanyakan: apa teknologi yang digunakan? Berapa lama pengerjaan? Berapa kali revisi? Bagaimana proses handover? Ada support setelah launch? Developer yang baik akan menjawab semua pertanyaan ini dengan jelas dan transparan." },
      { type:"cta", text:"Ingin tahu estimasi harga website untuk kebutuhan bisnis Anda? Gunakan kalkulator harga kami — gratis dan transparan." },
    ],
  },
  {
    slug: "landing-page-vs-company-profile",
    title: "Landing Page vs Company Profile: Pilih Yang Mana untuk Bisnis Anda?",
    category: "Tips & Panduan",
    catColor: "#f97316",
    date: "1 Jun 2026",
    readTime: "5 menit",
    excerpt: "Banyak pemilik UMKM bingung memilih antara landing page dan company profile. Keduanya punya fungsi berbeda. Temukan pilihan tepat untuk tujuan bisnis Anda.",
    cover: "from-violet-500 to-purple-600",
    emoji: "🎯",
    content: [
      { type:"p", text:"'Saya mau bikin website untuk bisnis saya.' Ketika Anda bilang itu ke developer, pertanyaan pertama yang bagus adalah: untuk tujuan apa? Apakah Anda ingin pelanggan langsung hubungi Anda? Atau ingin memperkenalkan bisnis Anda secara lengkap? Jawabannya menentukan jenis website yang tepat — dan bisa menghemat atau menghabiskan anggaran Anda." },
      { type:"h2", text:"Apa Itu Landing Page?" },
      { type:"p", text:"Landing page adalah halaman tunggal yang dirancang untuk satu tujuan spesifik: mendorong pengunjung melakukan satu aksi tertentu. Beli sekarang. Daftar sekarang. Hubungi sekarang. Tidak ada menu navigasi yang mengalihkan perhatian. Tidak ada 'tentang kami' yang panjang. Hanya satu alur cerita yang bermuara pada satu tombol." },
      { type:"p", text:"Bayangkan seorang salesperson terbaik yang fokus meyakinkan satu orang di depannya — itulah landing page. Setiap elemen di halaman itu ada untuk satu tujuan: konversi." },
      { type:"h2", text:"Apa Itu Company Profile?" },
      { type:"p", text:"Company profile adalah website multi-halaman yang memperkenalkan bisnis Anda secara menyeluruh. Ada halaman Home yang menyambut, About yang menceritakan perjalanan bisnis Anda, Services yang menjelaskan semua layanan, Portfolio yang membuktikan kemampuan, dan Contact untuk menghubungi. Ini seperti brosur digital yang lengkap dan selalu bisa diakses." },
      { type:"h2", text:"Kapan Pilih Landing Page?" },
      { type:"p", text:"Pilih landing page jika Anda menjalankan kampanye iklan (Google Ads atau Meta Ads) — karena landing page mengkonversi traffic iklan jauh lebih baik daripada website biasa. Juga cocok kalau Anda menjual satu produk atau layanan spesifik, bisnis Anda baru dan ingin validasi pasar dengan cepat, atau budget terbatas tapi ingin hasil yang terukur." },
      { type:"p", text:"Fakta menarik: landing page yang dioptimalkan bisa mengkonversi 2-5x lebih banyak pengunjung dibanding homepage biasa. Untuk iklan, ini perbedaan antara untung dan rugi." },
      { type:"h2", text:"Kapan Pilih Company Profile?" },
      { type:"p", text:"Pilih company profile jika bisnis Anda sudah establish dan butuh tampilan profesional, menawarkan banyak produk atau layanan yang perlu dijelaskan terpisah, target klien adalah B2B (business to business) yang biasanya melakukan riset mendalam, atau Anda ingin membangun brand awareness dan kepercayaan jangka panjang." },
      { type:"h2", text:"Solusi Terbaik: Kombinasi Keduanya" },
      { type:"p", text:"Banyak bisnis yang berkembang akhirnya punya keduanya. Company profile sebagai 'rumah utama' yang membangun brand, dan landing page terpisah untuk setiap kampanye iklan atau produk/promo spesifik. Ini strategi yang digunakan oleh bisnis-bisnis sukses — tapi Anda tidak harus memulai dari sana." },
      { type:"p", text:"Rekomendasi kami: mulai dengan landing page jika Anda baru mulai atau ingin cepat dapat leads. Upgrade ke company profile setelah bisnis Anda berkembang dan Anda tahu persis apa yang ingin dikomunikasikan ke pasar." },
      { type:"cta", text:"Masih bingung mana yang lebih cocok? Gunakan kalkulator harga kami untuk mendapat estimasi biaya keduanya." },
    ],
  },
  {
    slug: "cara-memilih-jasa-web-yang-tepat",
    title: "7 Hal yang Harus Dicek Sebelum Pakai Jasa Pembuat Website",
    category: "Tips & Panduan",
    catColor: "#f97316",
    date: "28 Mei 2026",
    readTime: "6 menit",
    excerpt: "Sudah banyak pemilik UMKM kecewa karena salah pilih jasa web. Dari website tidak mobile-friendly sampai developer hilang setelah bayar. Hindari kesalahan ini!",
    cover: "from-rose-500 to-pink-600",
    emoji: "🔍",
    content: [
      { type:"p", text:"'Saya sudah bayar Rp 3 juta, tapi website-nya tidak bisa dibuka di HP.' 'Developer-nya tidak bisa dihubungi lagi setelah selesai.' 'Website saya tidak pernah muncul di Google meski sudah setahun.' Cerita-cerita seperti ini terlalu sering kami dengar dari pemilik UMKM yang kecewa." },
      { type:"p", text:"Memilih jasa web yang tepat bukan soal harga termurah atau tampilan portofolio paling keren. Ada 7 hal krusial yang harus Anda cek sebelum mempercayakan website bisnis Anda kepada seseorang." },
      { type:"h2", text:"1. Kunjungi Portofolio Secara Langsung" },
      { type:"p", text:"Minta link website yang pernah mereka buat dan kunjungi sekarang. Jangan hanya lihat screenshot. Cek: apakah website-nya masih aktif dan bisa diakses? Apakah loading-nya cepat? Apakah tampilannya profesional di laptop dan di HP Anda? Kalau portofolio tidak bisa dikunjungi, itu red flag besar." },
      { type:"h2", text:"2. Test Mobile-Friendliness" },
      { type:"p", text:"Lebih dari 65% traffic website di Indonesia berasal dari smartphone. Website yang tidak mobile-friendly bukan hanya buruk untuk pengunjung, tapi juga dihukum Google — artinya tidak akan muncul di halaman pertama pencarian. Buka portofolio mereka di HP Anda. Apakah teksnya bisa dibaca? Apakah tombolnya mudah diklik jari? Apakah semua gambar tampil dengan benar?" },
      { type:"h2", text:"3. Pastikan Kepemilikan Aset" },
      { type:"p", text:"Ini yang paling sering diabaikan dan paling menyakitkan kalau salah. Tanyakan secara eksplisit: 'Setelah proyek selesai, apakah saya mendapat akses penuh ke semua file website, akun hosting, dan domain?' Beberapa developer tidak jujur soal ini dan menjadikan ketergantungan klien sebagai sumber income tambahan — Anda terpaksa terus bayar mereka untuk perubahan kecil sekalipun." },
      { type:"h2", text:"4. Cek Kecepatan Loading" },
      { type:"p", text:"Buka salah satu website di portofolio mereka, lalu buka GTmetrix.com atau PageSpeed.web.dev dan masukkan URL-nya. Lihat skor Performance-nya. Di atas 80 adalah standar minimal yang baik. Di bawah 50 adalah masalah serius yang akan merugikan bisnis Anda. Website lambat kehilangan 40% pengunjung bahkan sebelum halaman selesai dimuat." },
      { type:"h2", text:"5. Kejelasan Revisi dan Support Pasca-Launch" },
      { type:"p", text:"Seberapa banyak revisi yang termasuk dalam harga? Apa yang terjadi kalau ada bug setelah website diluncurkan? Ada support berapa lama? Semua ini harus tertulis jelas di proposal atau kontrak, bukan hanya janji lisan. Developer yang profesional tidak akan ragu menuliskan ini semua secara tertulis." },
      { type:"h2", text:"6. Transparansi Biaya Total" },
      { type:"p", text:"Harga awal yang tertera seringkali belum termasuk domain, hosting, plugin premium, atau konten. Minta breakdown biaya lengkap — termasuk biaya tahunan yang perlu Anda bayar ke depannya. Developer yang jujur akan menjelaskan semua ini di awal, bukan setelah Anda sudah bayar setengahnya." },
      { type:"h2", text:"7. Responsivitas Komunikasi" },
      { type:"p", text:"Kirim pesan ke developer tersebut dan perhatikan: seberapa cepat mereka merespons? Seberapa jelas penjelasan mereka? Apakah mereka mengajukan pertanyaan untuk memahami kebutuhan Anda, atau langsung kasih penawaran? Cara mereka berkomunikasi sebelum kontrak adalah cerminan bagaimana mereka akan bekerja selama proyek berlangsung." },
      { type:"p", text:"Developer yang baik akan banyak bertanya sebelum memberi harga: apa tujuan websitenya? Siapa target audiensnya? Fitur apa yang dibutuhkan? Kalau langsung kasih harga tanpa banyak tanya — hati-hati." },
      { type:"cta", text:"Kami percaya transparansi adalah fondasi kepercayaan. Hubungi kami dan rasakan sendiri perbedaannya." },
    ],
  },
  {
    slug: "fitur-website-toko-online",
    title: "7 Fitur Website yang Wajib Ada di Toko Online Anda",
    category: "E-Commerce",
    catColor: "#8b5cf6",
    date: "25 Mei 2026",
    readTime: "6 menit",
    excerpt: "Punya toko online tapi penjualan tidak meningkat? Mungkin ada fitur penting yang belum ada. Cek daftar 7 fitur ini untuk memaksimalkan konversi toko online Anda.",
    cover: "from-violet-500 to-indigo-600",
    emoji: "🛒",
    content: [
      { type:"p", text:"Anda sudah punya toko online. Sudah ada foto produk, sudah ada deskripsi, sudah ada harga. Tapi konversi masih rendah — banyak yang lihat, sedikit yang beli. Seringkali masalahnya bukan di produk Anda, tapi di pengalaman berbelanja yang kurang meyakinkan." },
      { type:"p", text:"Berikut 7 fitur yang membedakan toko online biasa dengan toko online yang benar-benar menjual." },
      { type:"h2", text:"1. Foto Produk Multi-Angle dengan Zoom" },
      { type:"p", text:"Pembeli online tidak bisa menyentuh produk Anda. Foto adalah satu-satunya jembatan antara produk dan kepercayaan mereka. Minimal 3-5 foto per produk: tampak depan, belakang, samping, detail tekstur/material, dan foto produk sedang dipakai/digunakan (lifestyle shot). Fitur zoom yang smooth di mobile sangat mengurangi keraguan pembeli dan meningkatkan konversi hingga 30%." },
      { type:"h2", text:"2. Tombol WhatsApp yang Strategis" },
      { type:"p", text:"Tempatkan tombol WhatsApp di setiap halaman produk, bukan hanya di halaman Contact. Ketika calon pembeli punya pertanyaan soal ukuran, warna, atau ketersediaan stok, mereka ingin jawaban cepat. Kalau tombol WA tidak mudah ditemukan, mereka akan pergi ke kompetitor yang lebih responsif. Tombol WA yang sudah pre-filled pesan ('Halo, saya tertarik dengan produk [nama produk]...') terbukti meningkatkan konversi." },
      { type:"h2", text:"3. Testimoni dengan Foto dan Nama Asli" },
      { type:"p", text:"'93% konsumen membaca ulasan sebelum membeli' — ini bukan sekadar angka. Testimoni dengan foto nyata, nama lengkap, dan detail pembelian (misalnya: 'Budi Santoso, Jakarta, membeli Batik Kawung ukuran L') jauh lebih meyakinkan daripada testimoni anonim. Kalau bisa tambahkan rating bintang dan tanggal pembelian untuk menunjukkan konsistensi kualitas Anda." },
      { type:"h2", text:"4. Informasi Pengiriman yang Kristal Jelas" },
      { type:"p", text:"Sebelum pembeli menanyakan, jawab dulu: 'Pengiriman ke seluruh Indonesia. Estimasi 2-4 hari kerja untuk Jawa, 3-7 hari untuk luar Jawa. Ongkir dihitung otomatis berdasarkan berat dan tujuan. Tersedia JNE, J&T, dan SiCepat. Cek ongkir sekarang.' Ketidakjelasan biaya pengiriman adalah penyebab nomor 1 cart abandonment di e-commerce Indonesia." },
      { type:"h2", text:"5. Filter dan Search Produk yang Intuitif" },
      { type:"p", text:"Ketika toko Anda sudah punya lebih dari 20 produk, navigasi menjadi krusial. Pembeli yang tidak bisa menemukan produk yang dicari dalam 30 detik akan meninggalkan toko Anda. Filter berdasarkan kategori, harga, ukuran, warna, dan ketersediaan stok — dikombinasikan dengan search bar yang pintar — bisa meningkatkan waktu kunjungan dan konversi secara signifikan." },
      { type:"h2", text:"6. Halaman FAQ yang Menjawab Sebelum Ditanya" },
      { type:"p", text:"Catat semua pertanyaan yang sering masuk ke WhatsApp Anda. Bisa jadi: 'Apakah ada garansi?', 'Bagaimana cara perawatannya?', 'Apakah bisa custom ukuran?', 'Berapa lama pengerjaan?'. Jadikan ini halaman FAQ yang detail. Ini menghemat waktu Anda, meningkatkan kepercayaan calon pembeli, dan membantu SEO karena Google menyukai halaman yang menjawab pertanyaan spesifik." },
      { type:"h2", text:"7. Checkout yang Sesederhana Mungkin" },
      { type:"p", text:"Setiap langkah tambahan dalam proses checkout adalah peluang hilangnya pembeli. Prinsipnya: sesedikit mungkin field yang harus diisi, sesedikit mungkin halaman yang harus dilewati. Form yang panjang dengan banyak field wajib adalah konversi killer. Minimal: nama, nomor WA atau email, dan alamat pengiriman. Sisanya bisa ditanyakan via WA setelah order masuk." },
      { type:"cta", text:"Ingin toko online yang lengkap dengan semua fitur ini? Mari diskusikan kebutuhan bisnis Anda." },
    ],
  },
  {
    slug: "website-lambat-bikin-rugi",
    title: "Kenapa Website Lambat Bisa Bikin Bisnis Anda Merugi",
    category: "Performa",
    catColor: "#ef4444",
    date: "20 Mei 2026",
    readTime: "5 menit",
    excerpt: "Setiap 1 detik keterlambatan loading website = 7% penurunan konversi. Data ini serius. Pelajari dampak nyata website lambat dan cara mengatasinya.",
    cover: "from-red-500 to-orange-500",
    emoji: "⚡",
    content: [
      { type:"p", text:"Anda punya produk bagus, harga kompetitif, dan sudah invest di iklan. Tapi kenapa penjualan tetap rendah? Mungkin jawabannya ada di sesuatu yang sering diabaikan: kecepatan website Anda." },
      { type:"p", text:"Google melaporkan bahwa 53% pengunjung mobile akan meninggalkan sebuah website kalau loading-nya lebih dari 3 detik. Lebih dari setengah calon pelanggan Anda hilang bahkan sebelum melihat apa yang Anda jual — hanya karena website terlalu lambat." },
      { type:"h2", text:"Angka yang Perlu Anda Tahu" },
      { type:"p", text:"Amazon — salah satu perusahaan paling obsesif soal performa — menghitung bahwa setiap 100 milidetik (0,1 detik!) keterlambatan merugikan mereka 1% penjualan. Walmart menemukan bahwa setiap 1 detik perbaikan kecepatan loading meningkatkan konversi mereka 2%. Untuk UMKM dengan omzet Rp 50 juta per bulan, website yang 2 detik lebih lambat bisa berarti kehilangan Rp 7 juta setiap bulan." },
      { type:"h2", text:"Dampak ke SEO yang Sering Diabaikan" },
      { type:"p", text:"Sejak Google merilis update algoritma Core Web Vitals pada 2021, kecepatan website menjadi faktor ranking yang resmi. Artinya: website lambat tidak hanya bikin pengunjung kabur, tapi juga membuat Google mendorong website Anda ke halaman yang lebih rendah di hasil pencarian. Kompetitor Anda yang punya website lebih cepat — bahkan dengan konten yang tidak lebih baik — bisa mengalahkan posisi Anda di Google." },
      { type:"h2", text:"5 Penyebab Website Lambat yang Paling Umum" },
      { type:"p", text:"Pertama, gambar yang tidak dioptimalkan. Ini penyebab nomor 1. Foto produk beresolusi tinggi yang langsung diupload tanpa kompresi bisa berukuran 3-5 MB per gambar. Halaman dengan 10 foto seperti itu butuh download 30-50 MB — butuh waktu 10+ detik di koneksi normal." },
      { type:"p", text:"Kedua, hosting murah dengan server yang lambat dan penuh sesak. Harga hosting Rp 50.000/bulan biasanya artinya satu server digunakan ratusan website sekaligus. Ketiga, terlalu banyak plugin WordPress yang tidak dibutuhkan. Keempat, tidak menggunakan CDN (Content Delivery Network). Kelima, kode yang tidak dioptimalkan — CSS dan JavaScript yang tidak di-minify dan di-compress." },
      { type:"h2", text:"Cara Mengecek Kecepatan Website Anda" },
      { type:"p", text:"Buka PageSpeed.web.dev dan masukkan URL website Anda. Anda akan mendapat skor 0-100 dengan detail apa yang perlu diperbaiki. Skor di atas 90 = Excellent, 70-89 = Good, 50-69 = Needs Improvement, di bawah 50 = Poor. Kalau website Anda di bawah 70, ada masalah serius yang perlu segera diperbaiki." },
      { type:"h2", text:"Solusi Praktis yang Bisa Dilakukan" },
      { type:"p", text:"Kompres semua gambar sebelum upload menggunakan TinyPNG.com (gratis). Targetkan setiap gambar di bawah 200 KB. Gunakan hosting dengan teknologi terbaru dan SSD storage. Pilih developer yang peduli performa — tanya skor PageSpeed dari website-website yang mereka buat sebelumnya. Website yang dibuat dengan Next.js misalnya, secara natural jauh lebih cepat dari WordPress." },
      { type:"cta", text:"Website Anda lambat? Kami spesialis website Next.js yang cepat, ringan, dan dioptimalkan untuk konversi." },
    ],
  },
  {
    slug: "panduan-seo-dasar-umkm",
    title: "Panduan SEO Dasar untuk UMKM: Mulai dari Mana?",
    category: "SEO",
    catColor: "#0d9488",
    date: "15 Mei 2026",
    readTime: "8 menit",
    excerpt: "SEO tidak harus rumit dan mahal. Dengan langkah-langkah dasar yang tepat, UMKM Anda bisa mulai muncul di halaman pertama Google tanpa bayar iklan.",
    cover: "from-teal-500 to-cyan-600",
    emoji: "🔎",
    content: [
      { type:"p", text:"Bayangkan warung bakso Anda muncul di halaman pertama Google ketika seseorang di kecamatan Anda mengetik 'bakso enak dekat sini'. Tanpa iklan berbayar. Tanpa bayar influencer. Gratis, setiap hari, selama Anda punya website yang dioptimalkan dengan benar." },
      { type:"p", text:"SEO (Search Engine Optimization) terdengar teknis dan rumit, tapi dasarnya sangat masuk akal: buat website yang mudah dipahami Google dan genuinely berguna bagi pengunjung. Artikel ini akan panduan langkah demi langkah khusus untuk pemilik UMKM yang baru mulai." },
      { type:"h2", text:"Mengapa SEO Adalah Investasi Terbaik untuk UMKM?" },
      { type:"p", text:"Iklan Google Ads berhenti mendatangkan traffic begitu Anda berhenti bayar. Tapi artikel blog yang Anda optimasi dengan baik bisa mendatangkan calon pelanggan selama 5 tahun ke depan tanpa biaya tambahan. Itulah kekuatan SEO — aset digital yang nilainya terus bertumbuh." },
      { type:"p", text:"93% pengalaman online dimulai dari mesin pencari. Dan 75% orang tidak pernah melewati halaman pertama Google. Kalau bisnis Anda tidak ada di halaman pertama, Anda praktis tidak ada di internet." },
      { type:"h2", text:"Langkah 1: Riset Kata Kunci yang Tepat" },
      { type:"p", text:"Sebelum menulis konten apapun, pahami kata apa yang diketik calon pelanggan Anda. Alat gratis: Google Keyword Planner, Google Trends, atau cukup ketik kata kunci di Google dan lihat 'Pencarian terkait' di bagian bawah halaman hasil." },
      { type:"p", text:"Fokus pada 'long-tail keywords' — kata kunci yang lebih spesifik dan lebih panjang. Contoh: daripada bersaing untuk kata 'katering' yang sangat kompetitif, targetkan 'katering prasmanan untuk pernikahan di Depok' yang jauh lebih mudah dimenangkan dan lebih relevan untuk bisnis lokal Anda." },
      { type:"h2", text:"Langkah 2: Optimasi Halaman (On-Page SEO)" },
      { type:"p", text:"Setiap halaman website harus punya: Title Tag yang mengandung kata kunci utama (maksimal 60 karakter), Meta Description yang menarik klik (maksimal 160 karakter), URL yang bersih seperti 'website.com/katering-depok' bukan 'website.com/?p=123', dan minimal satu gambar dengan alt text deskriptif." },
      { type:"p", text:"Gunakan kata kunci secara natural dalam konten — jangan dipaksakan. Google sekarang sangat pintar mendeteksi konten yang dibuat untuk manusia vs konten yang dibuat untuk mesin." },
      { type:"h2", text:"Langkah 3: Daftarkan di Google Business Profile" },
      { type:"p", text:"Untuk bisnis lokal, ini adalah langkah paling impactful yang bisa Anda lakukan hari ini — dan gratis. Google Business Profile membuat bisnis Anda muncul di Google Maps dan 'local pack' (3 bisnis yang muncul di peta ketika orang mencari layanan di area tertentu)." },
      { type:"p", text:"Lengkapi semua informasi: alamat, jam buka, nomor telepon, foto-foto, kategori bisnis yang tepat. Dan yang paling penting: minta pelanggan yang puas untuk memberikan ulasan Google. Ulasan positif adalah faktor ranking terkuat untuk local SEO." },
      { type:"h2", text:"Langkah 4: Buat Konten yang Menjawab Pertanyaan" },
      { type:"p", text:"Blog adalah mesin SEO jangka panjang yang paling powerful. Tulis artikel yang menjawab pertanyaan yang sering ditanyakan calon pelanggan Anda. Jasa bengkel? Tulis 'kapan harus ganti oli mobil'. Jasa katering? Tulis 'cara menghitung porsi makanan untuk 100 orang'. Jasa web? Tulis artikel ini." },
      { type:"p", text:"Satu artikel berkualitas yang dioptimalkan dengan baik bisa mendatangkan ratusan pengunjung organik setiap bulan — selama bertahun-tahun. Bayangkan punya 20 artikel seperti itu." },
      { type:"h2", text:"Langkah 5: Pastikan Website Anda Teknis SEO-Friendly" },
      { type:"p", text:"Loading cepat, mobile-friendly, menggunakan HTTPS (SSL), tidak ada broken links, dan sitemap yang benar — ini adalah fondasi teknis yang harus dipastikan ada. Website yang dibangun dengan teknologi modern seperti Next.js secara otomatis memenuhi sebagian besar kriteria teknis SEO ini." },
      { type:"cta", text:"Ingin website yang sudah SEO-ready dari hari pertama? Kami membangun website dengan best practices SEO built-in." },
    ],
  },
  {
    slug: "case-study-website-meningkatkan-omzet",
    title: "Case Study: Bagaimana Website Membantu UMKM Meningkatkan Omzet 3x",
    category: "Case Study",
    catColor: "#f59e0b",
    date: "10 Mei 2026",
    readTime: "8 menit",
    excerpt: "Kisah nyata bagaimana sebuah UMKM kuliner di Bandung berhasil meningkatkan omzet dari Rp 15 juta menjadi Rp 45 juta per bulan dalam 6 bulan setelah punya website.",
    cover: "from-amber-500 to-yellow-500",
    emoji: "📈",
    content: [
      { type:"p", text:"Pak Hendra Wijaya bukan orang yang mudah percaya dengan janji manis. Pemilik usaha katering rumahan di Bandung ini sudah 4 tahun menjalankan bisnisnya dengan cara yang sama: dari mulut ke mulut, grup WhatsApp keluarga, dan sesekali posting di Instagram. Omzetnya stabil di Rp 12-15 juta per bulan — tapi tidak pernah lebih dari itu." },
      { type:"p", text:"'Saya pikir katering itu ya memang segitu. Kalau mau lebih ya harus tambah karyawan, tambah peralatan, tambah modal besar,' kenangnya. Sampai seorang teman mengajak diskusi tentang website." },
      { type:"h2", text:"Kondisi Awal: Bisnis Bagus tapi Tidak Terlihat" },
      { type:"p", text:"Masakan Pak Hendra enak — itu tidak diragukan. Pelanggan lamanya selalu merekomendasikan ke teman dan keluarga. Tapi ada masalah fundamental: bisnis yang bagus ini tidak bisa ditemukan oleh orang yang belum mengenalnya. Ketika seseorang di Bandung mengetik 'katering murah Bandung' di Google, nama Pak Hendra tidak muncul sama sekali." },
      { type:"p", text:"Seluruh pemasaran bergantung pada referral — yang bagus, tapi tidak skalabel. Tidak ada cara bagi calon pelanggan baru untuk menemukan dan mengevaluasi bisnisnya secara mandiri." },
      { type:"h2", text:"Solusi: Website Sederhana tapi Tepat Sasaran" },
      { type:"p", text:"Di bulan Januari, Pak Hendra memutuskan membuat website. Bukan website mewah dengan banyak animasi dan fitur canggih. Tapi website yang strategis: landing page dengan foto makanan berkualitas tinggi, daftar paket katering dengan harga jelas, 15 testimoni pelanggan asli dengan foto, kalkulator estimasi harga berdasarkan jumlah tamu, dan form pemesanan sederhana." },
      { type:"p", text:"Yang tidak kalah penting: blog dengan artikel 'Tips Memilih Katering untuk Pernikahan', 'Berapa Porsi yang Dibutuhkan untuk 100 Tamu', dan 'Katering Prasmanan vs Katering Dus: Pilih Mana?'. Artikel-artikel ini dioptimalkan untuk kata kunci yang dicari calon pelanggannya." },
      { type:"h2", text:"Bulan 1-2: Masa Tenang yang Mengkhawatirkan" },
      { type:"p", text:"'Dua bulan pertama saya hampir menyesal,' kata Pak Hendra. Website sudah live, tapi tidak ada perubahan signifikan. Traffic hanya 20-30 pengunjung per hari, sebagian besar dari teman dan keluarga yang sengaja dikasih tahu. Satu atau dua leads per minggu dari website — hampir tidak berbeda dengan sebelumnya." },
      { type:"p", text:"Tapi ini normal. SEO butuh waktu. Google perlu waktu untuk 'memahami' website baru dan mulai menampilkannya di hasil pencarian. Yang penting adalah konsistensi — konten terus diperbarui, foto produk baru terus ditambahkan." },
      { type:"h2", text:"Bulan 3-4: Tanda-Tanda Positif Mulai Muncul" },
      { type:"p", text:"Di bulan ketiga, sesuatu berubah. Traffic organik mulai naik: dari 30 pengunjung/hari menjadi 80-100 pengunjung/hari. Beberapa keyword mulai masuk halaman 2-3 Google. Yang lebih penting: leads dari website mulai stabil — 3-5 per minggu, dan kualitasnya lebih baik dari sebelumnya." },
      { type:"p", text:"Calon pelanggan yang menghubungi lewat website sudah 'pre-qualified': mereka sudah baca paket harga, sudah lihat testimoni, sudah tahu kira-kira budget yang dibutuhkan. Proses closing jadi lebih cepat karena tidak perlu banyak penjelasan dari awal." },
      { type:"h2", text:"Bulan 5-6: Breakthrough yang Tidak Disangka" },
      { type:"p", text:"Di bulan kelima, website Pak Hendra masuk halaman 1 Google untuk keyword 'katering prasmanan Bandung' dan 'katering pernikahan Bandung murah'. Traffic melonjak ke 250-300 pengunjung/hari. Telepon dan pesan WhatsApp dari calon pelanggan baru tidak berhenti." },
      { type:"p", text:"Omzet bulan ke-5: Rp 38 juta. Bulan ke-6: Rp 45 juta. Naik 3x dari kondisi awal — hanya dari organic traffic website, tanpa satu rupiah pun dikeluarkan untuk iklan." },
      { type:"h2", text:"Apa yang Bisa Kita Pelajari?" },
      { type:"p", text:"Pertama, kualitas produk adalah fondasi — tidak ada website yang bisa menyelamatkan produk yang buruk. Kedua, website yang strategis jauh lebih valuable dari website yang sekadar cantik. Ketiga, SEO adalah investasi jangka panjang yang tidak bisa diharapkan memberikan hasil instan. Keempat, konten yang menjawab pertanyaan calon pelanggan adalah bahan bakar SEO yang paling efektif." },
      { type:"p", text:"Pak Hendra kini sedang mempersiapkan ekspansi dengan menambah 3 karyawan baru. 'Website itu bukan pengeluaran,' katanya. 'Itu modal usaha. Bedanya, modal ini terus bekerja bahkan saat saya sudah pulang ke rumah.'" },
      { type:"cta", text:"Siap memulai perjalanan pertumbuhan bisnis Anda? Kami bantu dari strategi website hingga SEO yang menghasilkan." },
    ],
  },
];

export const categories = [...new Set(articles.map(a=>a.category))];
